-- Run this in Supabase Dashboard: SQL Editor
-- Creates tables for Badminton Tournament Manager

-- Players
CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    gender TEXT NOT NULL,
    email TEXT NOT NULL,
    skill_level INT NOT NULL,
    group_name TEXT NOT NULL,
    assigned BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ
);

-- Config (key-value for group_names, subgroup_names, groups, detailed_groups)
CREATE TABLE IF NOT EXISTS config (
    key TEXT PRIMARY KEY,
    value_json JSONB NOT NULL
);

-- Standings per group (full Standings & Qualifiers row; group_name = internal key e.g. Group A)
CREATE TABLE IF NOT EXISTS standings (
    group_name TEXT PRIMARY KEY,
    team_display_name TEXT NOT NULL DEFAULT '',
    matches_played INT NOT NULL DEFAULT 0,
    clash_won INT NOT NULL DEFAULT 0,
    points INT NOT NULL DEFAULT 0,
    sets_won INT NOT NULL DEFAULT 0,
    sets_lost INT NOT NULL DEFAULT 0,
    set_difference INT NOT NULL DEFAULT 0,
    rally_points_won INT NOT NULL DEFAULT 0,
    rally_points_lost INT NOT NULL DEFAULT 0,
    rally_points_difference INT NOT NULL DEFAULT 0,
    clash_wins INT NOT NULL DEFAULT 0,
    total_points INT NOT NULL DEFAULT 0
);

-- App users (auth is separate; this stores app-level user metadata)
CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    created_by TEXT,
    created_at TEXT
);

-- Clash edit audit log
CREATE TABLE IF NOT EXISTS clash_edit_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT NOT NULL,
    editor TEXT,
    clash_key TEXT NOT NULL,
    match_number INT,
    action TEXT,
    original_data_json JSONB,
    new_data_json JSONB,
    reason TEXT
);

-- Tournament match results: full info per game (winner, score_display, points, set_scores, players, match_type, match_info)
CREATE TABLE IF NOT EXISTS tournament_matches (
    clash_key TEXT NOT NULL,
    match_index INT NOT NULL,
    data_json JSONB NOT NULL,
    PRIMARY KEY (clash_key, match_index)
);

-- Optional: enable RLS and add policies if you want row-level security.
-- By default the service_role key bypasses RLS.
-- ALTER TABLE players ENABLE ROW LEVEL SECURITY;
-- (add policies as needed)
